//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using AntlrExample;

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHelloListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class HelloBaseListener : IHelloListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.sts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSts([NotNull] HelloParser.StsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.sts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSts([NotNull] HelloParser.StsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.st"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSt([NotNull] HelloParser.StContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.st"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSt([NotNull] HelloParser.StContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.forst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForst([NotNull] HelloParser.ForstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.forst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForst([NotNull] HelloParser.ForstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.iFst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIFst([NotNull] HelloParser.IFstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.iFst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIFst([NotNull] HelloParser.IFstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] HelloParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] HelloParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.ast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAst([NotNull] HelloParser.AstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.ast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAst([NotNull] HelloParser.AstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterE([NotNull] HelloParser.EContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitE([NotNull] HelloParser.EContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterT([NotNull] HelloParser.TContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitT([NotNull] HelloParser.TContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterF([NotNull] HelloParser.FContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.f"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitF([NotNull] HelloParser.FContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
